/**:
  ros__parameters:

    port: /dev/ttyUSB0
    baudrate: 57600

    no_of_grippers: 2

    gripper_1:
      action_name: gripper_cmd
      servo_ids: [1]
      robot_ns: left

    gripper_2:
      action_name: gripper_cmd
      servo_ids: [2]
      robot_ns: right