moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ezgripper_dual_gen2_single_mount/ezgripper_controller

  ezgripper_dual_gen2_single_mount/ezgripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - left_ezgripper_knuckle_palm_L1_1
