moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ezgripper_controller

  ezgripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - left_ezgripper_knuckle_1